from .pooling import LehmerPool2d, SoftLehmerPool2d, GeneralizedLehmerPool2d
from .activation import GeneralizedSoftPlus
from .convolution import GeneralizedLehmerConvolution, GeneralizedPowerConvolution